#!/bin/bash

start1=$(date)
echo "$start1 StartDateTime"
echo ""

# Oracle DB Variables
sqllogin="TELELINKPRD/TELE#235#LINK#56#PRD@172.19.4.101:1521/nexggold"

export path1=/data01/shfiles/ra_reports/waba_report

cd "${path1}"
rm -f "${path1}"/*.txt

# Run SQLPlus script to extract data from Oracle
sqlplus -s "${sqllogin}" << EOF > "${path1}/sqlplus.log" 2>&1
SET ECHO OFF;
SET HEADING OFF;
SET PAGESIZE 0;
SET TERMOUT OFF;
SET VERIFY OFF;
SET LINESIZE 2500;
SET FEEDBACK OFF;
SET TRIMS ON;
SET NULL 0;

SPOOL /data01/shfiles/ra_reports/waba_report/rate.txt;

SELECT DISTINCT A.CUSTOMER_CODE||'|'||NVL(regexp_replace(USER_NAME,'[[:space:]]+',''),'NA')||'|'||CUSTOMER_NAME||'|'||EMAIL_ID||'|'||CREATION_DATE||'|'||CUSTOMER_STATUS||'|'||CUSTOMER_TYPE_CODE||'|'||
SUBSCRIPTION_CODE||'|'||A.TRANSACTION_CODE||'|'||SERVICE_NAME||'|'||SERVICE_MODE||'|'||CHARGE_TYPE||'|'||CUSTOMER_BASE_RATE||'|'||
CASE WHEN SERVICE_TYPE='Government' THEN 0 ELSE NVL(DTL_RATE,0) END||'|'||CHARGERATEUNIT||'|'||SERVICE_TYPE||'|'||EMPLOYEE_NAME||'|'||EMPLOYEE_EMAILID
FROM (SELECT A.CUSTOMER_CODE,UPPER(A.CUSTOMER_NAME) AS CUSTOMER_NAME,A.EMAIL_ID,TO_CHAR(A.CREATION_DATE,'YYYY-MM-DD HH24:MI:SS') AS CREATION_DATE,A.CUSTOMER_STATUS,A.CUSTOMER_TYPE_CODE,B.SUBSCRIPTION_CODE,D.SERVICE_NAME,
D.SERVICE_MODE,E.SERVICE_NAME AS SERVICE_TYPE,C.CHARGE_TYPE,C.CUSTOMER_BASE_RATE,F.CHARGERATEUNIT,C.TRANSACTION_CODE,G.EMPLOYEE_NAME,G.EMPLOYEE_EMAILID
FROM CUSTOMER_MST A, SUBSCRIPTION_MST B, SUBSCRIPTION_SERVICE_MST C, SERVICE_MST D, SERVICE_DTL E, SERVICE_RATING F, EMPLOYEE_MST G 
WHERE A.CUSTOMER_CODE=B.CUSTOMER_CODE AND A.CUSTOMER_STATUS='ACTIVE' AND B.SUBSCRIPTION_STATUS='ACTIVE' AND B.SUBSCRIPTION_CODE=C.SUBSCRIPTION_CODE AND C.SERVICE_CODE=D.SERVICE_CODE 
AND C.SERVICE_TYPE_CODE=E.SUB_SERVICE_CODE AND E.SUB_SERVICE_CODE!='SS0005' AND C.SERVICE_TYPE_CODE=F.SUB_SERVICE_CODE 
AND B.SALES_EMP_CODE=G.EMPLOYEE_CODE
) A 
INNER JOIN (SELECT DISTINCT TRANSACTION_CODE,UPPER(USER_NAME) AS USER_NAME FROM SUBSCRIPTION_SERV_ACC_DTL) B ON B.TRANSACTION_CODE=A.TRANSACTION_CODE
LEFT JOIN (SELECT DISTINCT CUSTOMER_CODE,B.CUSTOMER_BASE_RATE AS DTL_RATE FROM SUBSCRIPTION_MST A, SUBSCRIPTION_SERVICE_MST B
WHERE A.SUBSCRIPTION_CODE=B.SUBSCRIPTION_CODE AND A.SUBSCRIPTION_STATUS='ACTIVE' AND B.SERVICE_TYPE_CODE='SS0005') C ON C.CUSTOMER_CODE=A.CUSTOMER_CODE
ORDER BY 1;

SPOOL OFF;
exit;
EOF
