#!/bin/bash
satrt1=$(date)
echo $satrt1 StartDateTime
echo ""

export path1=/data01/shfiles/ra_reports/advance_credit
sqllogin="TELELINKPRD/TELE#235#LINK#56#PRD@172.19.4.101:1521/nexggold"

kill1=$(ps -eo comm,pid,etimes,cmd | grep advance_credit.sh | awk '{if($3 > 1800) print $2}')

if [ -z "$kill1" ]
then
echo "NO LONG RUNNING PROCESS FOUND TO BE KILL"
else
echo "LONG PROCESS KILLED"
kill -9 $kill1
fi

cd ${path1}
rm -f ${path1}/*.txt

sqlplus -s ${sqllogin} << EOF >/dev/null
SET ECHO OFF;
SET HEADING OFF;
SET PAGESIZE 0;
SET TERMOUT OFF; 
SET VERIFY OFF;
SET LINESIZE 2500;
SET FEEDBACK OFF;
SET TRIMS ON;
SET NULL 0;

SPOOL ${path1}/ADVANCE_CREDIT1.txt;

SELECT F.CUSTOMER_CODE||'|'||F.CUSTOMER_NAME||'|'||F.CUSTOMER_STATUS||'|'||TO_CHAR(A.CREATION_DATE,'YYYY-MM-DD HH24:MI:SS')||'|'||
A.SERVICE_CODE||'|'||A.ADVANCE_OPENING_BALANCE||'|'||A.ADVANCE_CREDIT_AMOUNT||'|'||A.PAYMENT_AMOUNT||'|'||
TO_CHAR(C.CREATION_DATE,'YYYY-MM-DD HH24:MI:SS')||'|'||C.NO_OF_DAYS||'|'||TO_CHAR(C.CREATION_DATE + C.NO_OF_DAYS,'YYYY-MM-DD HH24:MI:SS') AS DUE_DATE
FROM (SELECT SUBSCRIPTION_CODE,SERVICE_CODE,ADVANCE_OPENING_BALANCE,ADVANCE_CREDIT_AMOUNT,PAYMENT_AMOUNT,ACSTATUS,CREATION_DATE AS UPDATED_DATE,CREATION_DATE,
ROW_NUMBER() OVER (PARTITION BY SUBSCRIPTION_CODE ORDER BY 5 DESC ) AS ROW_NUM FROM ADVANCE_CREDIT_TRANS_DTL
WHERE ACSTATUS IN('PEN','COM') ORDER BY 5) A,
(SELECT SUBSCRIPTION_CODE,MAX(ROW_NUM) AS ROW_NUM FROM 
(SELECT SUBSCRIPTION_CODE,ADVANCE_OPENING_BALANCE,ADVANCE_CREDIT_AMOUNT,PAYMENT_AMOUNT,ACSTATUS,
CREATION_DATE,ROW_NUMBER() OVER (PARTITION BY SUBSCRIPTION_CODE ORDER BY 5 DESC ) AS ROW_NUM FROM ADVANCE_CREDIT_TRANS_DTL
WHERE ACSTATUS IN('PEN','COM') ORDER BY 5) GROUP BY SUBSCRIPTION_CODE) B,
(SELECT A.SUBSCRIPTION_CODE,A.CREATION_DATE,A.NO_OF_DAYS FROM ADVANCE_CREDIT_MST A,
(SELECT SUBSCRIPTION_CODE,MAX(CREATION_DATE) AS CREATION_DATE FROM ADVANCE_CREDIT_MST WHERE SUBSTR(REASON,1,1)='R' GROUP BY SUBSCRIPTION_CODE) B
WHERE A.SUBSCRIPTION_CODE=B.SUBSCRIPTION_CODE AND A.CREATION_DATE=B.CREATION_DATE AND SUBSTR(REASON,1,1)='R') C,
SUBSCRIPTION_MST D,CUSTOMER_MST F 
WHERE A.SUBSCRIPTION_CODE=B.SUBSCRIPTION_CODE AND A.ROW_NUM=B.ROW_NUM AND A.SUBSCRIPTION_CODE=C.SUBSCRIPTION_CODE AND
A.SUBSCRIPTION_CODE=D.SUBSCRIPTION_CODE AND D.CUSTOMER_CODE=F.CUSTOMER_CODE
AND ADVANCE_CREDIT_AMOUNT >0;

SPOOL OFF;
exit;
EOF

find ${path1}/*.txt -type f -size 0 -exec rm -rvf {} \;

if [ -f ${path1}/ADVANCE_CREDIT1.txt ]
then
echo "CUSTOMER_CODE|CUSTOMER_NAME|CUSTOMER_STATUS|ACTIVATION_DATE|SERVICE_CODE|ADVANCE_OPENING_BALANCE|ADVANCE_CREDIT_AMOUNT|PAYMENT_AMOUNT|ADVANCE_CREDIT_DATE|NO_OF_DAYS|COMPLETION_DATE |DUE_DATE" >${path1}/ADVANCE_CREDIT.txt
cat ${path1}/ADVANCE_CREDIT1.txt | awk '{print $0}' >>${path1}/ADVANCE_CREDIT.txt
java -jar SendMail.jar 2
fi

echo ""
end1=$(date)
echo $end1 EndDateTime
timediff1=$(printf "%s\n" $(( $(date -d "$end1" "+%s") - $(date -d "$satrt1" "+%s") )))
echo $timediff1 Sec
echo ""

