#!/bin/bash
satrt1=$(date)
echo $satrt1 StartDateTime
echo ""

sqllogin="TELELINKPRD/TELE#235#LINK#56#PRD@172.19.4.101:1521/nexggold"

export path1=/data01/shfiles/crm_rate_master

kill1=$(ps -eo comm,pid,etimes,cmd | grep crm_rate.sh | awk '{if($3 > 1800) print $2}')

if [ -z "$kill1" ]
then
echo "NO LONG RUNNING PROCESS FOUND TO BE KILL"
else
echo "LONG PROCESS KILLED"
kill -9 $kill1
fi

cd ${path1}
rm -f ${path1}/*.txt

sqlplus -s ${sqllogin} << EOF >/dev/null
SET ECHO OFF;
SET HEADING OFF; 
SET PAGESIZE 0;
SET TERMOUT OFF; 
SET VERIFY OFF;
SET LINESIZE 2500;
SET FEEDBACK OFF;
SET TRIMS ON;
SET NULL 0;

SPOOL ${path1}/RATE_LIST.txt;
SELECT DISTINCT A.CUSTOMER_CODE||'|'||NVL(regexp_replace(USER_NAME,'[[:space:]]+',''),'NA')||'|'||CUSTOMER_NAME||'|'||EMAIL_ID||'|'||CREATION_DATE||'|'||CUSTOMER_STATUS||'|'||CUSTOMER_TYPE_CODE||'|'||
SUBSCRIPTION_CODE||'|'||A.TRANSACTION_CODE||'|'||SERVICE_NAME||'|'||SERVICE_MODE||'|'||CHARGE_TYPE||'|'||CUSTOMER_BASE_RATE||'|'||
CASE WHEN SERVICE_TYPE='Government' THEN 0 ELSE NVL(DTL_RATE,0) END||'|'||CHARGERATEUNIT||'|'||SERVICE_TYPE||'|'||EMPLOYEE_NAME||'|'||EMPLOYEE_EMAILID
FROM (SELECT A.CUSTOMER_CODE,UPPER(A.CUSTOMER_NAME) AS CUSTOMER_NAME,A.EMAIL_ID,TO_CHAR(A.CREATION_DATE,'YYYY-MM-DD HH24:MI:SS') AS CREATION_DATE,A.CUSTOMER_STATUS,A.CUSTOMER_TYPE_CODE,B.SUBSCRIPTION_CODE,D.SERVICE_NAME,
D.SERVICE_MODE,E.SERVICE_NAME AS SERVICE_TYPE,C.CHARGE_TYPE,C.CUSTOMER_BASE_RATE,F.CHARGERATEUNIT,C.TRANSACTION_CODE,G.EMPLOYEE_NAME,G.EMPLOYEE_EMAILID
FROM CUSTOMER_MST A, SUBSCRIPTION_MST B, SUBSCRIPTION_SERVICE_MST C, SERVICE_MST D, SERVICE_DTL E, SERVICE_RATING F, EMPLOYEE_MST G 
WHERE A.CUSTOMER_CODE=B.CUSTOMER_CODE AND A.CUSTOMER_STATUS='ACTIVE' AND B.SUBSCRIPTION_STATUS='ACTIVE' AND B.SUBSCRIPTION_CODE=C.SUBSCRIPTION_CODE AND C.SERVICE_CODE=D.SERVICE_CODE 
AND C.SERVICE_TYPE_CODE=E.SUB_SERVICE_CODE AND E.SUB_SERVICE_CODE!='SS0005' AND C.SERVICE_TYPE_CODE=F.SUB_SERVICE_CODE 
AND B.SALES_EMP_CODE=G.EMPLOYEE_CODE
) A 
INNER JOIN (SELECT DISTINCT TRANSACTION_CODE,UPPER(USER_NAME) AS USER_NAME FROM SUBSCRIPTION_SERV_ACC_DTL) B ON B.TRANSACTION_CODE=A.TRANSACTION_CODE
LEFT JOIN (SELECT DISTINCT CUSTOMER_CODE,B.CUSTOMER_BASE_RATE AS DTL_RATE FROM SUBSCRIPTION_MST A, SUBSCRIPTION_SERVICE_MST B
WHERE A.SUBSCRIPTION_CODE=B.SUBSCRIPTION_CODE AND A.SUBSCRIPTION_STATUS='ACTIVE' AND B.SERVICE_TYPE_CODE='SS0005') C ON C.CUSTOMER_CODE=A.CUSTOMER_CODE
ORDER BY 1;

SPOOL OFF;
exit;
EOF

find ${path1}/*.txt -type f -size 0 -exec rm -rvf {} \;

if [ -f ${path1}/RATE_LIST.txt ]
then
mysql -h172.19.4.103 -uroot -pp*E9@r#Xnh sms_cdrs -vvv -w -e "TRUNCATE TABLE CRM_RATE_MST;" 2>/dev/null
mysql -h172.19.4.103 -uroot -pp*E9@r#Xnh sms_cdrs --local-infile -vvv -w -e "LOAD DATA local INFILE '${path1}/RATE_LIST.txt' INTO TABLE CRM_RATE_MST FIELDS TERMINATED BY '|' LINES TERMINATED BY '\n' (CUSTOMER_CODE,USER_NAME,CUSTOMER_NAME,CUSTOMER_EMAIL_ID,CREATION_DATE,CUSTOMER_STATUS,CUSTOMER_TYPE_CODE,SUBSCRIPTION_CODE,TRANSACTION_CODE,SERVICE_NAME,SERVICE_MODE,CHARGE_TYPE,CUSTOMER_BASE_RATE,DLT_RATE,CHARGERATEUNIT,SERVICE_TYPE,EMPLOYEE_NAME,EMPLOYEE_EMAILID);" 2>/dev/null
mysql -h172.19.4.103 -uroot -pp*E9@r#Xnh sms_cdrs -vvv -w -e "
UPDATE CRM_RATE_MST_copy A, CRM_RATE_MST B SET A.CUSTOMER_BASE_RATE=B.CUSTOMER_BASE_RATE,A.DLT_RATE=B.DLT_RATE,
A.CUSTOMER_NAME=B.CUSTOMER_NAME,A.CUSTOMER_EMAIL_ID=B.CUSTOMER_EMAIL_ID,A.CUSTOMER_TYPE_CODE=B.CUSTOMER_TYPE_CODE,
A.EMPLOYEE_NAME=B.EMPLOYEE_NAME,A.EMPLOYEE_EMAILID=B.EMPLOYEE_EMAILID
WHERE A.CUSTOMER_CODE=B.CUSTOMER_CODE AND A.SERVICE_TYPE=B.SERVICE_TYPE AND A.CHARGE_TYPE=B.CHARGE_TYPE;

INSERT INTO CRM_RATE_MST SELECT * FROM CRM_RATE_MST_copy;" 2>/dev/null
fi

mysql -h172.19.4.103 -uroot -pp*E9@r#Xnh nexg_hunt -vvv -w -e "

INSERT INTO nexg_hunt.SUBSCRIPTION_MST (CUSTOMER_CODE,USER_NAME,SERVICE_NAME,CHARGE_TYPE,CUSTOMER_BASE_RATE,DLT_RATE,CHARGERATEUNIT,SERVICE_TYPE)
SELECT CUSTOMER_CODE,USER_NAME,SERVICE_NAME,CHARGE_TYPE,CUSTOMER_BASE_RATE,DLT_RATE,CHARGERATEUNIT,SERVICE_TYPE FROM nexg_hunt.USER_NOT_FOUND
WHERE SERVICE_NAME='Bulk SMS';

UPDATE nexg_hunt.CUSTOMER_MST A, sms_cdrs.CRM_RATE_MST B SET A.SALES_EMP_NAME=B.EMPLOYEE_NAME,A.EMPLOYEE_EMAILID=B.EMPLOYEE_EMAILID WHERE A.CUSTOMER_CODE=B.CUSTOMER_CODE;
UPDATE nexg_hunt.CUSTOMER_MST A, nexg_hunt.CITY_NAME B SET A.ZONE=B.ZONE,A.STATE=B.STATE WHERE A.STATE=B.NAME_SHORT AND A.ZONE IS NULL;
UPDATE nexg_hunt.SUBSCRIPTION_MST A,(SELECT DISTINCT USER_NAME,PLATFORM FROM sms_cdrs.DAILY_SUMMARY) B SET A.PLATFORM=B.PLATFORM WHERE A.USER_NAME=B.USER_NAME;
UPDATE nexg_hunt.SUBSCRIPTION_MST_BKP A,(SELECT DISTINCT USER_NAME,PLATFORM FROM sms_cdrs.DAILY_SUMMARY) B SET A.PLATFORM=B.PLATFORM WHERE A.USER_NAME=B.USER_NAME;
UPDATE nexg_hunt.CUSTOMER_MST A, sms_cdrs.CRM_RATE_MST B SET A.CUSTOMER_NAME=B.CUSTOMER_NAME WHERE A.CUSTOMER_CODE=B.CUSTOMER_CODE;

" 2>/dev/null


sqllogin="TELELINKPRD/TELE#235#LINK#56#PRD@172.19.4.101:1521/nexggold"

for i in $(mysql -sN -h172.19.4.103 -uroot -pp*E9@r#Xnh nexg_hunt -e "SELECT DISTINCT CUSTOMER_CODE FROM CUST_NOT_FOUND" 2>/dev/null)
do
echo $i

export path1=/data01/shfiles/crm_rate_master

cd ${path1}
rm -f ${path1}/*.txt

sqlplus -s ${sqllogin} << EOF >/dev/null
SET ECHO OFF;
SET HEADING OFF; 
SET PAGESIZE 0;
SET TERMOUT OFF; 
SET VERIFY OFF;
SET LINESIZE 2500;
SET FEEDBACK OFF;
SET TRIMS ON;
SET NULL 0;

SPOOL ${path1}/cust.txt;
SELECT DISTINCT A.CUSTOMER_CODE||'|'||TO_CHAR(A.CREATION_DATE,'YYYY-MM-DD HH24:MI:SS')||'|'||A.CAF_NO||'|'||A.CUSTOMER_NAME||'|'||A.CUSTOMER_TYPE_CODE||'|'||A.REGISTRATION_NO||'|'||A.PAN_GIR_NO||'|'||
A.TEL_MARKET_LIC_NO||'|'||TO_CHAR(A.TEL_MARKET_LIC_VALIDITY,'YYYY-MM-DD HH24:MI:SS')||'|'||A.KEY_CONTACT_NAME||'|'||A.DESIGNATION_CODE||'|'||A.MOBILE_NO||'|'||A.OTHER_MOBILE_NO||'|'||
A.EMAIL_ID||'|'||A.CUSTOMER_STATUS||'|'||A.CREATED_BY||'|'||ENTITY_ID||'|"'||CASE WHEN C.ADDRESS_TYPE_CODE='00001' THEN ADDRESS END
||'"|'||STATE_CODE||'|'||CITY_CODE||'|'||PINCODE||'|'||B.SALES_EMP_CODE 
FROM CUSTOMER_MST A, SUBSCRIPTION_MST B, CUSTOMER_ADDRESS_MST C
WHERE A.CUSTOMER_CODE=B.CUSTOMER_CODE AND A.CUSTOMER_CODE=C.CUSTOMER_CODE AND C.ADDRESS_TYPE_CODE IN('00001') 
AND A.CUSTOMER_CODE IN('$i');
SPOOL OFF;
exit;
EOF

cat cust.txt | tr -d '\r' | awk -v RS='"' 'NR % 2 == 0 { gsub(/\n/, "") } { printf("%s%s", $0, RT) }' | sed '/^$/d' | tr -d '"' >cust1.txt

find ${path1}/*.txt -type f -size 0 -exec rm -rvf {} \;

if [ -f ${path1}/cust1.txt ]
then
mysql -h172.19.4.103 -uroot -pp*E9@r#Xnh nexg_hunt --local-infile -vvv -w -e "LOAD DATA local INFILE '${path1}/cust1.txt' INTO TABLE CUSTOMER_MST FIELDS TERMINATED BY '|' LINES TERMINATED BY '\n' 
(CUSTOMER_CODE,CREATION_DATE,CAF_NO,CUSTOMER_NAME,CUSTOMER_TYPE,REGISTRATION_NO,PAN_GIR_NO,TEL_MARKET_LIC_NO,TEL_MARKET_LIC_VALIDITY,
KEY_CONTACT_NAME,DESIGNATION_CODE,MOBILE_NO,OTHER_MOBILE_NO,EMAIL_ID,CUSTOMER_STATUS,CREATED_BY,ENTITY_ID,ADDRESS,
STATE,CITY,PINCODE,SALES_EMP_NAME);" 2>/dev/null

fi

mysql -h172.19.4.103 -uroot -pp*E9@r#Xnh nexg_hunt -vvv -w -e "

INSERT IGNORE INTO nexg_hunt.SUBSCRIPTION_MST (CUSTOMER_CODE,USER_NAME,SERVICE_NAME,CHARGE_TYPE,CUSTOMER_BASE_RATE,DLT_RATE,CHARGERATEUNIT,SERVICE_TYPE)
SELECT CUSTOMER_CODE,USER_NAME,SERVICE_NAME,CHARGE_TYPE,CUSTOMER_BASE_RATE,DLT_RATE,CHARGERATEUNIT,SERVICE_TYPE FROM nexg_hunt.USER_NOT_FOUND
WHERE SERVICE_NAME='Bulk SMS';


UPDATE nexg_hunt.CUSTOMER_MST A, sms_cdrs.CRM_RATE_MST B SET A.SALES_EMP_NAME=B.EMPLOYEE_NAME,A.EMPLOYEE_EMAILID=B.EMPLOYEE_EMAILID WHERE A.CUSTOMER_CODE=B.CUSTOMER_CODE;
UPDATE nexg_hunt.CUSTOMER_MST A, nexg_hunt.CITY_NAME B SET A.ZONE=B.ZONE,A.STATE=B.STATE WHERE A.STATE=B.NAME_SHORT AND A.ZONE IS NULL;
UPDATE nexg_hunt.SUBSCRIPTION_MST A,(SELECT DISTINCT USER_NAME,PLATFORM FROM sms_cdrs.DAILY_SUMMARY) B SET A.PLATFORM=B.PLATFORM WHERE A.USER_NAME=B.USER_NAME;
UPDATE nexg_hunt.SUBSCRIPTION_MST_BKP A,(SELECT DISTINCT USER_NAME,PLATFORM FROM sms_cdrs.DAILY_SUMMARY) B SET A.PLATFORM=B.PLATFORM WHERE A.USER_NAME=B.USER_NAME;
UPDATE nexg_hunt.CUSTOMER_MST A, sms_cdrs.CRM_RATE_MST B SET A.CUSTOMER_NAME=B.CUSTOMER_NAME WHERE A.CUSTOMER_CODE=B.CUSTOMER_CODE;

" 2>/dev/null
done


echo ""
end1=$(date)
echo $end1 EndDateTime
timediff1=$(printf "%s\n" $(( $(date -d "$end1" "+%s") - $(date -d "$satrt1" "+%s") )))
echo $timediff1 Sec
echo ""

